name: JupiterOne Integration Build Pipeline
description: Build & Release JupiterOne Integration
inputs:
  NPM_AUTH_TOKEN:
    description: 'NPM Auth Token for publishing JupiterOne integratino'
    required: true
runs:
  using: composite
  steps:
      # Build
      - name: Install dependencies
        run: yarn
        shell: bash
      - name: Run tests
        run: yarn test:ci
        shell: bash
      - name: Run build
        run: yarn build
        shell: bash

      # Publish
      - name: Fetch tags
        if: github.ref == 'refs/heads/master'
        run: |
          git fetch --tags
          if git describe --exact-match --match "v*.*.*" HEAD^2
          then
            echo "Found version commit tag. Publishing."
            echo "publish=true" >> $GITHUB_ENV
          else
            echo "Version commit tag not found. Not publishing."
          fi
        shell: bash
      - name: Publish
        if: env.publish == 'true'
        env:
          NPM_AUTH_TOKEN: ${{ inputs.NPM_AUTH_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc
          yarn
          npm publish
        shell: bash
        